language: python
python:
    - "3.5.0"
install:
    - pip install -r requirements.txt
    - python setup.py install
script: make test
after_success:
      export CODACY_PROJECT_TOKEN=de5cbf08632d4c07a4e1b23303e5e001
      python-codacy-coverage -r coverage.xml
